Pina selenium = 3.14.1
Isso é necessário para utilizar firefox mais novo nos testes robot.

Também foi necessário pinar urllib3 = 1.22 para evitar o erro:

    Error: There is a version conflict.
We already have: urllib3 1.25.9
but requests 2.18.4 requires 'urllib3<1.23,>=1.21.1'.